### ISSUE TITLE
[BUG] "run.bat" Script doesn't work if your Windows username contains a space character

### ISSUE THREAD

**Issue by BMAB2012** [matiaspedelhez/msfs_mouse_yoke#2]
**Describe the bug**
"run.bat" - Doesn't work properly if your windows username consists of two words (Contains a space character).

**To Reproduce**
Run "run.bat" as an administrator on an account with a username that has a space character.

**Expected behavior**
The script is supposed to install prerequisites and then launch the .py file.

**Screenshots**
After adding a "pause" line in the script before the "exit /b 0" I get this:
![image](https://github.com/matiaspedelhez/msfs_mouse_yoke/assets/67931416/14685b35-0961-41ea-9eef-10204e6c7379)

**Desktop specs (please complete the following information):**
 - OS: Win 11 x64
 - CPU: R7 7735HS

**Additional context**
My windows username is "Bruno Borges"

**Comment by matiaspedelhez** [comment]
Hi Bruno, thanks for describing your issue. 
Upon checking the code, I found that any space in the folder structure would make the script to fail. I have made the necessary changes to the code and will re-publish it with the corresponding updates.
Thank you!
