### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pedro-gt3250** [matiaspedelhez/msfs_mouse_yoke#3]
it wasnt running, i asked chat gpt why and it gave me this:

The script looks pretty solid at first glance, but I noticed a small typo that might be causing issues. In the following line:

```batch
echo Running mouse_yoke.py... >> "%LOGFILE%""
```

There's an extra double quote at the end. It should be:

```batch
echo Running mouse_yoke.py... >> "%LOGFILE%"
```

Remove that extra double quote, and it should be good to go.

Apart from that, if you're still encountering issues, it would be helpful to know what kind of problems or error messages you're getting. If there's a specific error or behavior you're trying to address, let me know, and we can troubleshoot it together! 🤙😄

**Comment by matiaspedelhez** [comment]
Hi Pedro, although the typo described above is correct, it is irrelevant and shouldn't affect the behavior of the script.

Could you provide, if any, the latest log generated by the script?
What Python version are you running? Are you able to see it when typing > `python -V` in a terminal?

**Comment by matiaspedelhez** [comment]
Closing this issue as no answer was given.
